#!/bin/sh
#
# Find duplicate files and make a executabe shell script for deleting them.  The shell script
# is commented on each line.  The user needs to edit the script and remove hash marks in
# front of files that he or she wants to delete.
#
# by Steve Crampton
# (Based loosely on a script found on the Internet; that script compared only filenames, whereas
# this script compares the hash codes of the files)
#
MD5L=md5list.tmp
D=do.tmp
OUTF=rem-duplicates.sh;
ESCCHARS='s/\([^a-zA-Z0-9./_-]\)/\\\1/g'
if [ $# -eq 0 ]; then
	DIR=.
else
	DIR=`echo $@ | sed $ESCCHARS`
fi
echo "#!/bin/sh" > $OUTF;
find $DIR -type f -print0 |
	xargs -0 -n1 md5sum -b |
	sort -k1,32 > $MD5L
echo -n "'/" > $D
cat $MD5L |
	awk '{ print $1 }' |
	uniq -d |
	awk '{ printf("(%s)|", $1) }' >> $D
echo "(nothing)/ { if (seen[\$1]++ != 1) \$1=\"rm \"; else \$1=\"#rm \"; print \$0 }' $MD5L" >> $D
cat $D | xargs awk |
	sed -e 's/\(.*\)\*\.\/\(.*\)/\1\2/' -e $ESCCHARS -e 's/^\\#rm\\ \\/#rm /g' -e 's/^rm\\ \\/rm /g' |
	awk '{ if (NR % 2 == 1) $1="rm" ; print $0 }' >> $OUTF
chmod u+x $OUTF
rm $MD5L $D
exit 0
