#!/bin/sh
MD5L=md5list.tmp
D=do.tmp
OUTF=rem-duplicates.sh;
ESCCHARS='s/\([^a-zA-Z0-9./_-]\)/\\\1/g'
if [ $# -eq 0 ]; then
	DIR=.
else
	DIR=`echo $@ | sed $ESCCHARS`
fi
echo "#! /bin/sh" > $OUTF;
find $DIR -type f -print0 |
	xargs -0 -n1 md5sum -b |
	sort -k1,32 > $MD5L
echo -n "'/" > $D
cat $MD5L |
	awk '{ print $1 }' |
	uniq -d |
	awk '{ printf("(%s)|", $1) }' >> $D
echo "(nothing)/ { print \$2 \$3 \$4 \$5 \$6 \$7 }' $MD5L" >> $D
cat $D | xargs awk |
	sed 's/\(.*\)\*\.\/\(.*\)/\1\2/' |
	sed $ESCCHARS |
	sed 's/\(.*\)/#rm \1/' >> $OUTF
chmod u+x $OUTF
rm $MD5L $D
exit 0
