#!/bin/sh
#
# Make a Photo Webpage, complete with thumbnails and slideshow.
#
# by Steve Crampton
#
# 1) Create an empty folder with a memorable name, e.g., Oct09
# 2) cd into that folder
# 3) Create a folder called images
# 4) Put all of your original .jpg images (full sized) into the images folder
# 5) Run this script one level up from your images folder, e.g., in Oct09
# 6) This script takes the page title as a command-line argument, e.g.,
#    ./MakePhotoWebpage "Halloween Pics"
#
rm -rf thumbs 2>/dev/null
mkdir thumbs
ls -1 images |
     grep -i jpg |
     sed 's/\(.*\)/convert images\/\1 -resize x125 -quality 60 thumbs\/thumb-\1/' |
     /bin/sh
rm pics.css 2>/dev/null
echo "body	{"                                    > pics.css
echo "		background-color: rgb(127,127,127);" >> pics.css
echo "		text-align: center;"     >> pics.css
echo "		}"                       >> pics.css
echo "h1	{"                       >> pics.css
echo "		margin: 0;"              >> pics.css
echo "		text-align: center;"     >> pics.css
echo "		color: Navy;"            >> pics.css
echo "		}"                       >> pics.css
echo "h2	{"                       >> pics.css
echo "		margin: 0;"              >> pics.css
echo "		text-align: center;"     >> pics.css
echo "		}"                       >> pics.css
echo "h3	{"                       >> pics.css
echo "		margin: 3px;"            >> pics.css
echo "		text-align: center;"     >> pics.css
echo "		}"                       >> pics.css
echo "a		{"                       >> pics.css
echo "		color: Black;"           >> pics.css
echo "		}"                       >> pics.css
echo "a:hover	{"                       >> pics.css
echo "		color: Blue;"            >> pics.css
echo "		}"                       >> pics.css
echo ".pic	{"                       >> pics.css
echo "		margin: 10px;"           >> pics.css
echo "		}"                       >> pics.css
rm index.html 2>/dev/null
echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"  > index.html
echo "<html>"                                                            >> index.html
echo "<head>"                                                            >> index.html
echo "	<meta content=\"text/html; charset=ISO-8859-1\" http-equiv=\"content-type\">" >> index.html
if [ $# -ne 0 ]; then
     echo "	<title>$1</title>"                                       >> index.html
else
     echo "	<title>Picture Gallery</title>"                          >> index.html
fi
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"pics.css\">"   >> index.html
echo "  <script language=\"javascript\">"                                >> index.html
echo "    <!-- Hide script from old browers"                             >> index.html
echo "    function ShowSlides() {"                                       >> index.html
echo "      wOptions = \"width=1024,height=676,resizable=yes,scrollbars=no,toolbar=no\"" >> index.html
echo "      wOptions += \",location=no,directories=no,status=no,menubar=no,copyhistory=no\"" >> index.html
echo "      slideWindow = window.open('slideshow.html', 'Slideshow', wOptions)" >> index.html
echo "    }"                                                             >> index.html
echo "    // End hiding script -->"                                      >> index.html
echo "  </script>"                                                       >> index.html
echo "</head>"                                                           >> index.html
echo "<body>"                                                            >> index.html
export TZ=EST
DATE=`date +"%b %-e, %Y"`
if [ $# -ne 0 ]; then
     echo "     <h1>$1 (last updated $DATE)</h1>"                        >> index.html
else
     echo "     <h1>Picture Gallery (last updated $DATE)</h1>"           >> index.html
fi
echo "        <h2>Click on a thumbnail to see the full-sized image.  <a href=\"javascript:ShowSlides()\">Slideshow</a></h2>" >> index.html
ls -1 images |
     sort -r |
     sed 's/\(.*\)/	<span class="pic"><a href="images\/\1" target="_blank"><img src="thumbs\/thumb-\1" alt="\1" \/><\/a><\/span>/' >> index.html
if [ $# -gt 1 ]; then
    echo "	<h3>$2</h3>"                                             >> index.html
fi
echo "</body>"                                                           >> index.html
echo "</html>"                                                           >> index.html
rm -rf slides 2>/dev/null
mkdir slides
ls -1 images |
     sed 's/\(.*\)/convert images\/\1 -resize 1006x658 -quality 60 temp.jpg\nconvert temp.jpg -mattecolor "rgb(127,127,127)" -frame \$(((1008 - `identify -format "%w" temp.jpg`) \/ 2))x$(((660 - `identify -format "%h" temp.jpg`) \/ 2)) slides\/slide-\1/' |
     /bin/sh
rm array.tmp 2>/dev/null
ls -1r slides/*.* | sed 's/\(.*\)/                              "\1",/' |
     head -c-2 > array.tmp
rm slideshow.html 2>/dev/null
echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">"  > slideshow.html
echo "<html>"                                                          >> slideshow.html
echo "<head>"                                                          >> slideshow.html
echo "  <meta content=\"text/html; charset=ISO-8859-1\" http-equiv=\"content-type\">" >> slideshow.html
if [ $# -ne 0 ]; then
     echo "     <title>$1 Slideshow (last updated $DATE)</title>"         >> slideshow.html
else
     echo "     <title>Slideshow (last updated $DATE)</title>"            >> slideshow.html
fi
echo "  <link rel=\"stylesheet\" type=\"text/css\" href=\"pics.css\">"    >> slideshow.html
echo "  <script language=\"javascript\">"                                 >> slideshow.html
echo "    <!-- Hide script from old browsers"                             >> slideshow.html
echo "    var theImages = new Array("                                     >> slideshow.html
cat array.tmp >> slideshow.html
echo ""                                                                   >> slideshow.html
echo "                              )"                                    >> slideshow.html
echo "    var thisPic = 0"                                                >> slideshow.html
echo "    function startcycle() {"                                        >> slideshow.html
echo "      if (document.images) {"                                       >> slideshow.html
echo "        setTimeout(\"cycle()\", 5000)"                              >> slideshow.html
echo "      }"                                                            >> slideshow.html
echo "    }"                                                              >> slideshow.html
echo "    function cycle() {"                                             >> slideshow.html
echo "      thisPic++"                                                    >> slideshow.html
NUMBER_OF_IMAGES=`cat array.tmp | awk '{ } END { print NR }'`
echo "      if (thisPic >= $NUMBER_OF_IMAGES) {"                          >> slideshow.html
echo "        thisPic = 0"                                                >> slideshow.html
echo "      }"                                                            >> slideshow.html
echo "      document.thePic.src = theImages[thisPic]"                     >> slideshow.html
echo "      setTimeout(\"cycle()\", 5000)"                                >> slideshow.html
echo "    }"                                                              >> slideshow.html
echo "    // End hiding script from old browsers -->"                     >> slideshow.html
echo "  </script>"                                                        >> slideshow.html
echo "</head>"                                                            >> slideshow.html
echo "<body onload=\"startcycle()\">"                                     >> slideshow.html
FIRST_IMAGE=`ls -1r slides/*.* | head -n1`
echo "  <img src=\"$FIRST_IMAGE\" name=\"thePic\" width=1008 height=660>" >> slideshow.html
echo "</body>"                                                            >> slideshow.html
echo "</html>"                                                            >> slideshow.html
rm array.tmp temp.jpg
exit 0
